export const HOME = '/'
export const DEFAULT = '/*'
export const USER = '/user'
export const PROFILE = '/user/profile'
export const ANNOUNCEMENTS = '/announcements'
export const MANAGEMENT = '/management'
export const NEWANNOUNCEMENT = '/announcements/new'
export const NEWHOME = '/home/:id'